name: Build Android

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 1) Gerar arquivo de ativação (.alf)
      - name: Request Unity Activation File
        id: get_alf
        uses: game-ci/unity-request-activation-file@v2

      - name: Upload .alf file
        uses: actions/upload-artifact@v4
        with:
          name: Unity_Activation_File
          path: ${{ steps.get_alf.outputs.activation-file }}

      # 2) Ativar Unity quando você enviar o .ulf 
      - name: Activate Unity
        if: env.UNITY_LICENSE != ''
        uses: game-ci/unity-activate@v1
        with:
          unityLicense: ${{ env.UNITY_LICENSE }}

      # 3) Build Android (Unity Builder v4)
      - name: Build Android
        uses: game-ci/unity-builder@v4
        with:
          targetPlatform: Android

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Android-APK
          path: build/Android/*.apk
