name: Build Godot Android

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Godot
        run: |
          wget https://downloads.tuxfamily.org/godotengine/3.5.2/mono/Godot_v3.5.2-stable_mono_linux_headless_64.zip
          unzip Godot_v3.5.2-stable_mono_linux_headless_64.zip -d godot

      - name: Build APK
        run: |
          ./godot/Godot_v3.5.2-stable_mono_linux_headless_64 \
          --path . \
          --export-release "Android" build.apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: build.apk
